---
apiVersion: skaffold/v2beta16
kind: Config
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
profiles:
  - name: emarket-pipeline-target-1-non-prod
    deploy:
      kubectl:
        manifests:
          - k8s/emarket-pipeline-target-1-non-prod/*.yaml
  - name: emarket-pipeline-target-2-prod
    deploy:
      kubectl:
        manifests:
          - k8s/emarket-pipeline-target-2-prod/*.yaml