---
apiVersion: skaffold/v2beta16
kind: Config
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
profiles:
  - name: non-prod
    deploy:
      kubectl:
        manifests:
          - k8s/nonprod/*.yaml
  - name: gke-prod
    deploy:
      kubectl:
        manifests:
          - k8s/prod/*.yaml