---
apiVersion: skaffold/v2beta16
kind: Config
deploy:
  kubectl:
    manifests:
      - k8s/*.yaml
profiles:
  - name: non-prod
    deploy:
      kubectl:
        manifests:
          - k8s/non-prod/*.yaml
  - name: prod
    deploy:
      kubectl:
        manifests:
          - k8s/prod/*.yaml